###

Post http://localhost:3000/api/user
Content-Type: application/json

{
    "id": "cb561ab5-41f0-4162-a7e9-9a7b933a697a",
    "first_name": "Fahrezi",
    "last_name": "Rizqiawan",
    "phone": "0843534545",
    "nationality": "Indonesia",
    "email": "fahrezi@gmail.com",
    "password": "password",
    "createdAt": "21 August 2024 12:37:05 A.M",
    "updatedAt": "21 August 2024 12:37:05 A.M"
}

###

post http://localhost:3000/api/logout
Content-Type: application/json

{
    "email": "fahrezi@gmail.com",
    "password": "password"
}